/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Asrivo.view;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import Asrivo.controller.AnggotaController;
import javax.swing.JButton;

/**
 *
 * @author Dell
 */
public class FormAnggota extends javax.swing.JFrame {
  
    /**
     * Creates new form FormAnggota
     */
    AnggotaController controller;
    public FormAnggota() {
        initComponents();
        controller = new AnggotaController(this);
        controller.clearForm();
        controller.tampil();
    }

    public JComboBox<String> getCboJenisKelamin() {
        return CboJenisKelamin;
    }

    public void setCboJenisKelamin(JComboBox<String> CboJenisKelamin) {
        this.CboJenisKelamin = CboJenisKelamin;
    }

    public JTable getTabelAnggota() {
        return tabelAnggota;
    }

    public void setTabelAnggota(JTable tabelAnggota) {
        this.tabelAnggota = tabelAnggota;
    }


    public JTextField getTxtKodeAnggota() {
        return TxtKodeAnggota;
    }

    public JTextField getTxtNamaAnggota() {
        return TxtNamaAnggota;
    }

    public JTextField getTxtAlamat() {
        return TxtAlamat;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public JButton getBtnUpdate() {
        return btnUpdate;
    }

    public JButton getBtninsert() {
        return btninsert;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        KodeAnggota = new javax.swing.JLabel();
        TxtKodeAnggota = new javax.swing.JTextField();
        NamaAnggota = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.JLabel();
        TxtNamaAnggota = new javax.swing.JTextField();
        TxtAlamat = new javax.swing.JTextField();
        CboJenisKelamin = new javax.swing.JComboBox<>();
        Alamat = new javax.swing.JLabel();
        btninsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\527254-hacker.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        KodeAnggota.setForeground(new java.awt.Color(255, 255, 0));
        KodeAnggota.setText("Kode Anggota");
        getContentPane().add(KodeAnggota);
        KodeAnggota.setBounds(20, 30, 100, 16);

        TxtKodeAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtKodeAnggotaActionPerformed(evt);
            }
        });
        getContentPane().add(TxtKodeAnggota);
        TxtKodeAnggota.setBounds(120, 30, 250, 22);

        NamaAnggota.setForeground(new java.awt.Color(255, 255, 0));
        NamaAnggota.setText("Nama Anggota");
        getContentPane().add(NamaAnggota);
        NamaAnggota.setBounds(20, 70, 90, 16);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 90, 0, 0);

        JenisKelamin.setForeground(new java.awt.Color(255, 255, 0));
        JenisKelamin.setText("Jenis Kelamin");
        getContentPane().add(JenisKelamin);
        JenisKelamin.setBounds(20, 160, 100, 16);
        getContentPane().add(TxtNamaAnggota);
        TxtNamaAnggota.setBounds(120, 70, 250, 22);
        getContentPane().add(TxtAlamat);
        TxtAlamat.setBounds(120, 110, 250, 22);

        CboJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CboJenisKelamin);
        CboJenisKelamin.setBounds(120, 160, 130, 22);

        Alamat.setForeground(new java.awt.Color(255, 255, 0));
        Alamat.setText("Alamat");
        getContentPane().add(Alamat);
        Alamat.setBounds(20, 110, 80, 16);

        btninsert.setBackground(new java.awt.Color(255, 127, 0));
        btninsert.setText("INSERT");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        getContentPane().add(btninsert);
        btninsert.setBounds(10, 210, 70, 23);

        btnUpdate.setBackground(new java.awt.Color(255, 127, 0));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(100, 210, 80, 23);

        btnDelete.setBackground(new java.awt.Color(255, 127, 0));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(210, 210, 80, 23);

        btnCancel.setBackground(new java.awt.Color(255, 127, 0));
        btnCancel.setText("CANCEL");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(300, 210, 90, 23);

        tabelAnggota.setBackground(new java.awt.Color(255, 127, 0));
        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Anggota", "Nama Anggota", "Alamat", "Jenis Kelamin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAnggota.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelAnggotaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelAnggota);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 270, 360, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Colorful-lines-strokes-abstract-pictures_iphone_640x960.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -510, 920, 760);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Colorful-lines-strokes-abstract-pictures_m.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 210, 410, 380);

        setSize(new java.awt.Dimension(408, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtKodeAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtKodeAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtKodeAnggotaActionPerformed

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.clearForm();
        controller.tampil();
    }//GEN-LAST:event_btninsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.clearForm();
        controller.tampil();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        // TODO add your handling code here:
        controller.getAnggota();
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    private void tabelAnggotaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelAnggotaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAnggotaAncestorAdded

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.clearForm();
        controller.tampil();
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAnggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAnggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JComboBox<String> CboJenisKelamin;
    private javax.swing.JLabel JenisKelamin;
    private javax.swing.JLabel KodeAnggota;
    private javax.swing.JLabel NamaAnggota;
    private javax.swing.JTextField TxtAlamat;
    private javax.swing.JTextField TxtKodeAnggota;
    private javax.swing.JTextField TxtNamaAnggota;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btninsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelAnggota;
    // End of variables declaration//GEN-END:variables
}
